### ISSUE TITLE
Support of FS / ADLSV2 / S3 filesystems

### ISSUE THREAD

**Issue by aureliesalmon** [ebiznext/comet-data-pipeline#13]
## Description
Currently CDP has been tested on top of HDFS. 
The goal here is to make it work on S3 filesystems.
This is probably more a DevOps ticket.

## Solution proposition
The work required here is to make sure that the Hadoop client API work seamlessly with the S3 filesystem. The proposed Ptah to make it work is as follows : 
1. Install S3 on your laptop check this gist (https://gist.github.com/jcaddel/730dc58f4653adf33e4f)
2. Create sample tests to make sure that the ingestion framework works well on S3 filesystems

## Additional context

# Life cycle

## Complexity estimation
T-Shirt Size: XS, S, M, L. If you would recommend XL or more, we advise you to discuss with the community how to split this issue.

**Comment by hayssams** [comment]
Support checked on those fs
