### ISSUE TITLE
[ENHANCEMENT] - JDBC delivery of Metrics lacks a full test 

### ISSUE THREAD

**Issue by cchepelov** [ebiznext/comet-data-pipeline#146]
## Description
JDBC delivery of Metrics lacks a full test where data is actually written via JDBC and confirmed read back correctly.

## Expected behavior
After an ingestion run is performed, on a Comet configured to do so, Metrics data get pushed via JDBC and can be read back

## Current Behavior
There is a test that does this in `JsonIngestionJobSpecNoIndexJdbcMetricsJdbcAuditSpec` but for good or bad reason, no data is actually pushed out.

For now, the test effectively tests that the table can be created and queried against (which is good) but doesn't actually validate the contents and serdes.

## Steps to reproduce
1. run JsonIngestionJobSpecNoIndexJdbcMetricsJdbcAuditSpec 
2. see that it passes even though it assers the metric records in the JDBC table are Nil.

## Context
While building #142, the target test case appeared to actually deliver no metrics, and no other test appeared to do. Need more internals' expertise to ensure data gets generated (additional info in the schema? More input data?)

# Life cycle

## Possible implementation
- possibly fill more input data
- possibly expand the schema definition (or work in a more detailed schema definition where metrics are actually requested)

## Complexity estimation
T-Shirt Size: S
(it's probably 'just' a question of an appropriate dataset, possibly cues from `StatDescJobSpec`)

**Comment by hayssams** [comment]
I have a yelp dataset and yml file that handle metrics correctly. 
Will update the code add soon and make it work as a test case for parquet metrics

**Comment by hayssams** [comment]
Just submitted PR #151
This issue should wait for #149 to be implemented since @AmineSagaama is redesigning the Metrics ADT

**Comment by cchepelov** [comment]
Sounds great!

Thanks for the heads-up wrt not rushing the integration
