### ISSUE TITLE
Enforce Scala style

### ISSUE THREAD

**Issue by mmenestret** [ebiznext/comet-data-pipeline#18]
- Set up Scalafmt
- Set up Wartremover

**Comment by hayssams** [comment]
Scalafmt setup
Wartremover too strict to handle the generic nature of this software that deals with a lot of untyped dataset. Since we are loading untyped dataset and ingesting them for typing.

**Comment by mmenestret** [comment]
We can still set it up and ignore the dirty parts, still better than nothing IMO.
I'd rather go for `sclafix` though.
