### ISSUE TITLE
[BUG] - Fix generate-encryptionYml behavior

### ISSUE THREAD

**Issue by mmenestret** [ebiznext/comet-data-pipeline#185]
## Description

1. When schemas are generated with `generate-encryptionYml` command, post-encrypt yml attributes should have `"NONE"` as a privacy rule since that is has already been handled by pre-encrypt and, in addition, attributes in post-encrypt get back their real primitive types which might not be compatible with a privacy rule since they enforce the need to have a `string` primitive type.

2. When schemas are generated with `generate-encryptionYml` command, fields with "HIDE" as privacy rule in pre-encrypt yml should have a `required` field changed in post-encrypt since that field is guaranteed to be empty after anonymization and thus will not pass the condition  :

```
val colPatternOK = optionalColIsEmpty || colPatternIsValid
```

since the column attribute `required` is left unchanged in post-encrypt.

## Expected behavior

It would be possible to process a dataset with the pre-encrypt schema and then, later, ingest the result with the post-encrypt schema.

## Possible implementation

We could probably : 
- Set all `required` fields to `false` for attributes with privacy rule to `"HIDE"` in the post-encrypt generated yml
- Set to `"NONE"` all privacy rules in the post-encrypt schemas

## Complexity estimation
T-Shirt Size: S

**Comment by mmenestret** [comment]
And probably fields with `"HIDE` as privacy rule in pre-encrypt yml should change `required` in post-encrypt since that field is guaranteed to be empty after anonymization.

**Comment by hayssams** [comment]
Why not add --disable-encryption to comet watch && comet ingest
