### ISSUE TITLE
[BUG] - Fix BigQuery Indexation

### ISSUE THREAD

**Issue by mmenestret** [ebiznext/comet-data-pipeline#191]
## Description
Whether to index or not in BigQuery seems to depend on the wrong conditions.

## Expected behavior
If set in the schema metadata or in settings, the indexation in BQ should work as expected.

## Current Behavior
For the indexation in BQ to work, one needs to :
- Set index in `reference.conf` to "BigQuery" and activate audit which does not seem to have any relation.

## Steps to reproduce
1. Deactivate `audit` in `reference.conf`
2. and / or do not set `index` to `"BigQuery"` in `reference.conf`
3. Set `index` to `"BQ"` in your schema metadata
4. See that it does not index in BQ

## Possible implementation
```
val res = settings.comet.audit.index match {
      case _: IndexSinkSettings.BigQuery if settings.comet.audit.active =>
        runBQSparkConnector()
```

This is the only way to trigger BQ indexation.

It should rely on either schema's metadata is set to `"BQ"` and / or (probably or ?) if index in settings is set to `"BigQuery"` (and it should probably be the same expected string in both places, "BQ" or "BigQuery" not both).

## Complexity estimation
T-Shirt Size:  S

**Comment by hayssams** [comment]
I've linked the PR #190 
Could you check it
