### ISSUE TITLE
[BUG] - BigQuery can't infer the Schema of the Dataset if the Table is based on partitioning

### ISSUE THREAD

**Issue by AmineSagaama** [ebiznext/comet-data-pipeline#217]
## Description
When we want to partition a Table in BigQuery, we have to explicitly specify the schema of the Dataset, otherwise we will have such an error : 
BigQuery error in load operation: Table with field based partitioning must have a schema.'

## Expected behavior
BigQuery can import a partitioned table without any errors.

## Current Behavior
An error is raised when we try to import a **Partitioned** Table from an existing dataset (cloud storage)

## Possible implementation
We have to specify the schema of the Table before importing it.

## Complexity estimation
T-Medium Size: M

**Comment by mhdkassir** [comment]
@AmineSagaama I think this issue can be closed

**Comment by AmineSagaama** [comment]
fixed here #219
