### ISSUE TITLE
Data Compaction

### ISSUE THREAD

**Issue by aureliesalmon** [ebiznext/comet-data-pipeline#3]
## Description
When saving files as parquet or orc or whatever, the optimal number of partitions depend on the dataset size,  number of records, the size of each record and the HDFS block size.

The goal of this feature is to optimise the number of partitions during the write phase on HDFS.
### Solution 1 : Naive Compaction
1. Save the file in a temporary location
2. Get the dataset size on HDFS.
3. Divide the dataset size by the  HDFS block size to get the number of partitions
4. Save the dataset to the target HDFS location with the computed number of partitions

The main drawback of this approach is that we need to save the file twice.

### Solution 2 : Sampling
1. Get a percentage of the records in the dataframe before saving it.
2. Save it to a temporary location
3. Estimate the size of the final dataset on HDFS based on the size of the sample on HDFS
4. Compute the number of partitions based on this estimation
5. Save the dataset to the target HDFS location with the computed number of partitions

The Naive solution is in fact identical to the Sampling one with a sampling percentage of 100%.

### Solution 3 : Absolute Compaction
The number of partitions is defined by the user at the schema level.

## Considered alternatives
N.A.
## Additional context
N.A.

# Life cycle

## Possible implementation
Add an attribute "compaction" at the Schema / Domain / Application level. that may take one of the following values : 
0 : Means no sampling, apply the naïve approach
0.x : A value between 0.0001 and 0.9999 means apply the sampling approach
1..99999: A value between 1 and Max Int means apply an absolute compaction with this value. 
## Complexity estimation
T-Shirt Size: XS, S, M, L. If you would recommend XL or more, we advise you to discuss with the community how to split this issue.
S

**Comment by hayssams** [comment]
done
