### ISSUE TITLE
[BUG] - Overwrite mode with group as false may not behave as expected (possibility, not checked)

### ISSUE THREAD

**Issue by tiboun** [ebiznext/comet-data-pipeline#307]
## Description
For whatever reason, if the watcher is down for a long time, many files may land into the landing area and all match one specific metadata which has overwrite mode and group as false.

For the ingestion of those files, we may have not the last data in the silver area.

## Expected behavior
I expect that the last landed file should be in the silver area.

## Current Behavior
Not checked, but we may have a random one. Furthermore, if max dag run is not set to 1, we may have a strange behavior on the output dataset, since many ingestion job are running simulatenously.

## Steps to reproduce
Not checked

## Context

# Life cycle

## Possible implementation
1. Order by date in the landing area in order to import them to the bronze area. Make sure that storage has at least millisecond precision.
2. In this condition, we may import all data to bronze area but trigger ingestion job only for the oldest one. 

How to avoid simultaneous ingestion of this dataset ?
We may create specific dags when output is in overwrite mode and set max active run to 1 in order to queue ingestion requests.

## Complexity estimation
Don't know

**Comment by hayssams** [comment]
This request has been implemented on 8/5/20 by sorting files on time & name as follow:
        .sortBy(r => (r.getModificationTime, r.getPath.getName))

Closing issue
