### ISSUE TITLE
Credentials from Azure blob store

### ISSUE THREAD

**Issue by ashitabh** [ebiznext/comet-data-pipeline#347]
## Description
Documentation shows image of Azure databricks and data lake on Azure storage , but I am unable to find place to provide access key for blob store 

Could you please update doc/ or just share details on where to provide password(access key)  for wasb

**Comment by hayssams** [comment]
To access ADFS, I provide the account key through the core-site.xml file as shown below.
Not sure this is what you are asking for:

<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<configuration>
    <property>
        <name>fs.azure.account.key.ebizcomet.dfs.core.windows.net</name>
        <value>YpdjCZcTiLE7kidEZBqK7HgLiWAD32MQpxCq5wRq+RcfOgqusLzdXtIUCf541YYarYmm2GsSQ3eyUnV15eQs0Q==</value>
    </property>
    <property>
        <name>fs.default.name</name>
        <value>abfs://cometfs@ebizcomet.dfs.core.windows.net/</value>
    </property>

</configuration>

**Comment by hayssams** [comment]
By looking @microsoft documentation it seems that this this configuration may also be passed as en env env during cluster creation see below
https://docs.microsoft.com/fr-fr/azure/databricks/data/data-sources/azure/azure-storage#access-azure-blob-storage-using-the-rdd-api

**Comment by hayssams** [comment]
By adding defining a custom application file and adding the key with the spark.hadoop. prefix this should work too
This doc also explain where to specify custom spark options https://docs.microsoft.com/fr-fr/azure/databricks/data/data-sources/azure/azure-datalake-gen2#rdd-api

Will improve the doc soon

**Comment by ashitabh** [comment]
thanks a lot
