### ISSUE TITLE
[BUG] - Scripted field(s) can only be the last field(s) of the schema

### ISSUE THREAD

**Issue by mmenestret** [ebiznext/comet-data-pipeline#384]
## Description

If a schema contains a scripted field, the ingestion fails if it is not the last field of the schema

## Expected behavior

It should be possible to have a scripted field anywhere in the schema

**Comment by hayssams** [comment]
Do you think that we should just improve the doc and say that scripted fields should be at the end of the schema or is it worth it to make its possible for scripted fields to be present anywhere in the schema ?

**Comment by mmenestret** [comment]
I don't know if the solution with scripted fields at the end work when
there are more than one scripted fields.
I'll try to test that one and if that's the case maybe just an update of
the doc could be enough.

Le ven. 20 nov. 2020 à 11:06, Hayssam Saleh <notifications@github.com> a
écrit :

**Comment by hayssams** [comment]
It should work
Let us know if it does not

**Comment by mhdqassir** [comment]
I've had this issue and having defined all the script fields at the end worked fine. 
I think it's better to have the script fields at the end, because they are extra fields that we add to the initial schema defined by the ingested data.

**Comment by cchepelov** [comment]
Good news that multiple scripted fields are supported (it’d probably be great to prove+pin this in a unit test) even with the « at the end » limitation.
Some documentation and perhaps a « pin test » to demonstrate we know and it’s « intended » (or at least, not a surprise) to say that scripted fields not at the end are illegal.

Does keeping this limitation compel the user, at the other end of the lake, to have the scripted fields at the end of the output schema? Wouldn’t that be a little irrelevant from the point of view of the ultimate data consumer?
