### ISSUE TITLE
[WIP][FEATURE] - Use BigQuery DML MERGE statement in case of a BigQuery Table

### ISSUE THREAD

**Issue by AmineSagaama** [ebiznext/comet-data-pipeline#402]
## Description
MERGE statement is a powerful construct and an optimization pattern that combines **INSERT**, **UPDATE** and **DELETE** operations on a table into an _upsert_ operation based on values matched from another table.
Currently, we use Spark transformations, like **windowing** and **except** to deal with the merge scenarios.

The good news is that BigQuery natively supports MERGE operation.
So, in the case of a merge of tables in BigQuery, it will be better to use directly BigQuery client, to apply the merge
with a query like : 

```
MERGE target_table 
USING source_table
ON merge_condition
WHEN MATCHED [AND search_condition]
    THEN update_statement | delete_statement
WHEN NOT MATCHED [AND search_condition]
    THEN insert_statement 
WHEN NOT MATCHED BY SOURCE [AND search_condition]
    THEN update_statement | delete_statement;
```

For other Distributed File Systems and Data Warehouses like HDFS, Cloud Storage, Snowflake
we will use the comet generic engine.

## Complexity estimation
T-Shirt Size: L
Don't forget to tag this issue as a 'good first issue' if you think it is appropriate!

**Comment by hayssams** [comment]
The idea is interesting except that Comet currently use the merge statement exclusively for file ingestion. This requires to use the Spark engine and cannot be done using the BQ Engine.

However, we may effectively use the Spark merge statement already available in delta lake. We probably need to make Comet delta lake compliant as a new feature.
