### ISSUE TITLE
[BUG] - datasets are not ingested and processed by chronological order of their timestamp

### ISSUE THREAD

**Issue by olivierschultz** [ebiznext/comet-data-pipeline#473]
## Description
Datasets are ingested and processed based on the property `getModificationTime` of the file system, from oldest to most recent, rather than in chronological order of creation (for example: my_dataset_20210328100000, then my_dataset_20210329100000 and finally my_dataset_20210330100000).

## Expected behavior
comet should sort the datasets by their timestamp instead of the arrival date on the file system ( based on `getModificationTime`) from oldest to most recent.

## Current Behavior
comet ingests and processes the datasets according to the arrival date on the file system (getModificationTime).
- What is affected? data.
- Who is it affecting? Everyone who finds themselves in this particular case.
- When does it occur? When a same dataset from different days is copied in the incoming area not in chronological order.
- Where does it happen? /

## Steps to reproduce
1. Copy a dataset from different days to the incoming area my_dataset_20210328100000.csv.gz, my_dataset_20210329100000.csv.gz, my_dataset_20210330100000.csv.gz where the modification_time property doesn't reflect the chronological order of the dataset.
2. Execute comet on these datasets.
3. Check your big query tables to see that some rows in your big query tables were overwritten by the old data.

## Context
To better illustrate my case, let's take an example:
We had a case in our project where we had a serie of datasets with their timestamps appended to the file name, waiting on an external system for a few days, let's say:
- my_dataset_20210328100000.csv.gz
- my_dataset_20210329100000.csv.gz
- my_dataset_20210330100000.csv.gz

Later on, the datasets were copied to the incoming area:
- my_dataset_20210330100000.csv.gz (modification_time: 1617184800000)
- my_dataset_20210328100000.csv.gz (modification_time: 1617186600000)
- my_dataset_20210329100000.csv.gz (modification_time: 1617187500000)

As you can see from the filesystem-based modification_time property, for some reasons, my_dataset_20200330100000.csv.gz arrived after my_dataset_20200328100000 and my_dataset_20200329100000.

So, according to this method used to ingest and process data [list](https://github.com/ebiznext/comet-data-pipeline/blob/4558ae6c7d1d9eeb03e7e9b488b460a471e1a1c7/src/main/scala/com/ebiznext/comet/schema/handlers/StorageHandler.scala#L177), comet will process the datasets from oldest to most recent on the file system:
- my_dataset_20210330100000.csv.gz (modification_time: 1617184800000)
- my_dataset_20210328100000.csv.gz (modification_time: 1617186600000)
- my_dataset_20210329100000.csv.gz (modification_time: 1617187500000)

Thus, later on it will lead to unexpected behaviors such as data (from 30/03/2021) in some big query tables will be overwritten by the old data (28/03/2021) and so on.

# Life cycle

## Possible implementation
To be discussed

## Complexity estimation
To be determined

**Comment by mhdkassir** [comment]
A solution to this issue would be to have the possibility to choose one criteria for sorting files (modification time or name of the files) instead of the current behavior which sort the files by modification time and then by name.  There is no need to consider the modification time when when a timestamp is present in the name of the files. 
This can be done using an configuration element with a default value and the possibility to override it using an environment variable.

**Comment by hayssams** [comment]
@olivierschultz
Comet works as expected. Please resubmit as a feature

**Comment by olivierschultz** [comment]
@hayssams @mhdkassir Closed this issue in favor of #474.
