### ISSUE TITLE
[FEATURE] - Add an option to Ingest and process datasets in chronological order of creation

### ISSUE THREAD

**Issue by olivierschultz** [ebiznext/comet-data-pipeline#474]
## Description
Datasets are ingested and processed based on the property `getModificationTime` of the file system, from oldest to most recent, rather than in chronological order of creation (for example: my_dataset_20210328100000, then my_dataset_20210329100000 and finally my_dataset_20210330100000), which is the expected behavior of comet.

To better illustrate my case, let's take an example:
We had a case in our project where we had a serie of datasets with their timestamps appended to the file name, waiting on an external system for a few days, let's say:
- my_dataset_20210328100000.csv.gz
- my_dataset_20210329100000.csv.gz
- my_dataset_20210330100000.csv.gz

Later on, the datasets were copied to the incoming area:
- my_dataset_20210330100000.csv.gz (modification_time: 1617184800000)
- my_dataset_20210328100000.csv.gz (modification_time: 1617186600000)
- my_dataset_20210329100000.csv.gz (modification_time: 1617187500000)

As you can see from the filesystem-based modification_time property, for some reasons, my_dataset_20200330100000.csv.gz arrived before my_dataset_20200328100000 and my_dataset_20200329100000.

So, according to this method used to ingest and process data [list](https://github.com/ebiznext/comet-data-pipeline/blob/4558ae6c7d1d9eeb03e7e9b488b460a471e1a1c7/src/main/scala/com/ebiznext/comet/schema/handlers/StorageHandler.scala#L177), comet will process the datasets from oldest to most recent on the file system:
- my_dataset_20210330100000.csv.gz (modification_time: 1617184800000)
- my_dataset_20210328100000.csv.gz (modification_time: 1617186600000)
- my_dataset_20210329100000.csv.gz (modification_time: 1617187500000)

Thus, later on it will lead to unexpected behaviors such as data (from 30/03/2021) in some big query tables will be overwritten by the old data (28/03/2021) and so on.

Is this feature related to any client using Comet? How? Yes, anyone who finds themselves in this particular case.

## Solution proposition
comet could sort the datasets by their timestamp (if present in the file name) instead of the arrival date on the file system ( based on getModificationTime) from oldest to most recent.

## Considered alternatives
Copy files in the incoming area to match timestamp and the property modification_time on the file system.

# Life cycle

## Possible implementation
As stated by @mhdkassir, a solution would be to have the possibility to choose one criteria for sorting files (modification time or name of the files) instead of the current behavior which sort the files by modification time and then by name. There is no need to consider the modification time when when a timestamp is present in the name of the files.
This can be done using an configuration element with a default value and the possibility to override it using an environment variable.

## Complexity estimation
S

**Comment by hayssams** [comment]
I like the solution proposed by @mhdkassir that allows us to propose multiple strategies.
First we probably should have a plugin class that may be called on the folder and that returns the ordered list. Let call this trait  "LoadStrategy"

Second, we may propose multiple strategies by default in the codebase such as :
IngestionTimeStrategy: Order by time and then by name
IngestioNameStrategy: Order by name only

And add key in the reference.conf file something similar to :
load-strategy=com.ebiznext.load.strategy.IngestionTimeStrategy
load-strategy=$COMET_LOAD_STRATEGY
