### ISSUE TITLE
[BUG] - GCP - dataproc jobs fail silently when yml files are invalid

### ISSUE THREAD

**Issue by abdelhakimbendjabeur** [ebiznext/comet-data-pipeline#525]
## Description
When using dataproc to launch load jobs with invalid yaml files, the job exits with success but it logs that it has failed to read the yml file.

## Expected behavior
Job should fail to be alerted whenever this happens.

## Current Behavior
Job is marked as successful. check image below

![comet_bug](https://user-images.githubusercontent.com/25367149/119356057-48fc0100-bca6-11eb-8e05-d82a9f99f55f.png)

## Steps to reproduce
1.Put an invalid yaml
2. launch a load job
3. check logs

## Context
Load csv files from gcs to bigquery using cloud composer + dataproc

## Possible implementation
NA

**Comment by hayssams** [comment]
Invalid YAML files are no more reported as warning but as errors.
Published in version : 0.2.1-SNAPSHOT

**Comment by mhdkassir** [comment]
@hayssams @abdelhakimbendjabeur the fix that was applied for this issue applies a very restrictive control. All the yaml files are checked when starting Comet and any invalid yaml file will throw a runtime Exception and stops the execution even if the yaml file is not directly used for the ingestion or Job. For example if Domain Z is not valid and I want to run ingestion Domain X, ingestion will be blocked. 
I suggest to change the behavior in the following way : 
- global validation when Comet starts prints error( or warn) messages  concerning the different yaml syntax/serializing issues
- An error is thrown if and only if the yaml file is concerned by the running process (ingestion or job).
What do you think ?

**Comment by hayssams** [comment]
@mhdkassir  @abdelhakimbendjabeur 
I suggest that we add a new command ```comet validate``` that exit the program with an error and print error only when any other command is run. In your DAG you would need to put a extra task that run ```comet validate``` first.

Another option would simply be to add an extra option COMET_VALIDATE_SCHEMA, if set would stop the process or else simply print error message.

Which one has your preference ?

**Comment by hayssams** [comment]
after talking with @mhdkassir we agreed on implementing both. The second case if implemented using 
```
validate-on-load = false
validate-on-load = ${?COMET_VALIDATE_ON_LOAD}
```
