### ISSUE TITLE
[FEATURE] - Infer schema

### ISSUE THREAD

**Issue by hayssams** [ebiznext/comet-data-pipeline#83]
## Description
Same utility to create schema faster

## Solution proposition
Handle bot CSV & JSON files. CSV may or may not have a header.

## Additional context
This could include:
- Design diagrams
- Documentation draft
- Migration strategy
- Adoption and teachability for this feature

# Life cycle

## Possible implementation
Describe here a brief for any contributor wishing to work on this issue

## Complexity estimation
T-Shirt Size: XS, S, M, L. If you would recommend XL or more, we advise you to discuss with the community how to split this issue.
Don't forget to tag this issue as a 'good first issue' if you think it is appropriate!

**Comment by mhdkassir** [comment]
I think this feature can be closed , @faresismail96  do you confirm ?

**Comment by faresismail96** [comment]
yes it can be closed @mhdkassir

**Comment by mhdkassir** [comment]
closed after the merge #84
