### ISSUE TITLE
[BUG] - cannot safely run unit tests in parallel

### ISSUE THREAD

**Issue by cchepelov** [ebiznext/comet-data-pipeline#95]
## Description
Attempting to run unit tests in parallel hits several race conditions, which renders a "green" result a lucky occurrence in the wrong environment

## Expected behavior
Running `sbt test` or any other equivalent (such as running tests under IDEA) succeeds all the time

## Current Behavior
Running tests under IDEA on a multicore machine may result in tests randomly failing.

## Leads pursued so far

* A first-order approach of the problem is that multiple unit test instances may attempt to call  `HdfsStorageHandler#write` method on the same file target (e.g. `/metadata/types/types.yml`), and this method contains a race condition.
   * The race condition in `HdfsStorageHandler#write` is that it first deletes the destination path (if it exists) then proceeds with creating a new file, then fills its contents. If Unit Test Instance #1 attempts to write `/metadata/types/types.yml` at roughly the same time as Unit Test Instance #2 does the same, this can result in UTI #1 believing the file is now written, attempting to read back from it, while UTI #2 begins its own "delete then overwrite process".
   * An 'obvious fix' for this is to have the `HdfsStorageHandler#write` first write into a uniquely named file, then `rename()` from the temporary path to the target path using the `Rename.Options.OVERWRITE` flag (this requires to use Hadoop's FileContext rather than FileSystem)
   * This 'obvious fix' fails as while an HDFS FileSystem implementation must guarantee that the Create, Close, Delete and Rename operations are atomic, the *rename-and-overwrite* operation is *not* atomic. Indeed, it is implemented by AbstractFileSystem as the sequence of a delete then a rename-without-OVERWRITE. This contains effectively the same race condition as the initial issue.
   * Even with implementing a "keep trying" approach to solve the delete-and-rename race, this only serves to expose another race: every unit test begins by destroying every single file in the Comet data directory (`cleanMetadata` and `cleanDatasets` methods). Which means that every Unit Test begins by destroying any files needed by already-runing unit tests, dooming them.

* A second-order approach of the problem would be to modify TestHelper so that each test suite instance receives a distinct `tempPath`, effectively insulating each test unit instance from each other.
   * This fails, as the domain descriptors in `test/resources/sample/*.yml` refer to absolute paths *(one of them appears to be rooted in @hayssams own /Users directory)* ⇒ *a possible solution to this would include performing some replacements in `TestHelper#init` while pulling the resource into the storageHandler.*
   * This fails, as the Settings.comet lazy instance effectfully reads from a global variable (COMET_DATASETS, COMET_METADATA, COMET_AUDIT_PATH, etc.) which is set (differently) in each TestHelper instance. The net result of this is that each TestHelper "sees" the single comet instance, started with parameters that belong to just one of them… Which also defeats the purpose of attempting to have a single path.

* A third-order approach of the problem would be to change the initialization logic of the comet instance, so that rather than relying on a set of global variables, one *could* spin multiple distinct comet instances in the same JVM, each insulated one from another.

## Complexity estimation

* simplest approach (disable parallel test execution): **XS** ; just set `parallelExecution in Test := false` in the `build.sbt` file.

* initialization order change: no less than **M**. 
   * The benefit is primarily tests and speed of running tests (which *is* a quality). There are *no* expected benefits on production code, since the usage pattern will still be "run one JVM per task, which will run its singular Comet instance".
   * There should be a way to avoid changing too much code, by modifying the `lazy val comet: Comet` in `Settings` to be a summoner: `def comet(implicit env: Comet): Comet = env`, and provide a way to initialize the "global" Comet instance from an explicitly-provided Config instance. 
      * `SparkJob` would effectively spin up its implicit Comet instance near the beginning and keep doing everything as before
      * Unit tests would `ConfigFactory.load()` a Config *and then* override every key that needs to be distinct from any other unit test instance, *then* spin a Comet instance, *then* carry on with the tasks.
      * This may still be noisy, with "implicit comet: Comet" creeping up in many places and a couple nontrivial changes (e.g. StorageArea and its Jackson serdes)
      * it would still be adviseable to perform substitutions in domain descriptor files as they are injected into each Comet instance from resource files.

**Comment by hayssams** [comment]
@cchepelov 
We could add a root directory and have all paths in the reference.conf fiel to be relative to this root var. The root var would be evaluated differently for each running test, solving the race issue we have.

The new reference.conf fil would look like this :

root = "/tmp"
root=${?COMET_ROOT}
datasets = "$root/datasets"
datasets = ${?COMET_DATASETS}

metadata = "$root/metadata"
metadata = ${?COMET_METADATA}

tmpdir = "$root/comet_tmp"
tmpdir = ${?COMET_TMPDIR}


By using the existing env vars, we could still be able to use absolute paths.

**Comment by cchepelov** [comment]
Indeed, we can factor out the root directory in the configuration, this will certainly be helpful. 

This does however not solve the root issue in the _test_ context: currently, there can be only one `Comet`instance (as it is reached via the `Settings`object), short of boxing every test suite into its own child classloader.

Are there any consumers of Comet as a library out there, or are all users of the `Settings#comet`value contained within this project?

**Comment by mhdkassir** [comment]
@cchepelov I think this issue can be closed

**Comment by cchepelov** [comment]
indeed. Did I forgot to add a "Closes" in the PR ?
