### ISSUE TITLE
[FEATURE] - support delivering audits to JDBC

### ISSUE THREAD

**Issue by cchepelov** [ebiznext/comet-data-pipeline#96]
## Description
Audits & Metrics can be delivered to BigQuery for now. 
It would be useful to support delivering to a JDBC database instead

Work is already in progress (@hayssams)

**Comment by cchepelov** [comment]
Got _a_ something that seems to push into JDBC, but #95 is now firmly in my way to test that we got exactly what we expect to into the Audit table.

**Comment by hayssams** [comment]
Done
